### ISSUE TITLE
关于该插件延迟加载的问题

### ISSUE THREAD

**Issue by QuincySx** [Rickdroid/l2d233ForTypechoNew#1]
大佬有没有解决过，我研究了一下没有找到方案。

**Comment by giteRdroid** [comment]
其实我不理解你的延迟加载的问题是怎么回事。
虽然我可能不懂怎么解决。。
但是你可以简单说说经过。

**Comment by QuincySx** [comment]
上来就直接加载，我这边有肉眼可见的卡顿。我已经解决了。

**Comment by giteRdroid** [comment]
能分享一下你的解决方案吗？

**Comment by QuincySx** [comment]
https://github.com/QuincySx/l2d233ForTypechoNew/blob/master/js/waifu-tips.js#L268
主要修改了加载时机。

https://github.com/QuincySx/l2d233ForTypechoNew/blob/master/Plugin.php#L36
修改了加载时初始化是隐藏的。

**Comment by giteRdroid** [comment]
OK，谢谢分享！！
